version: '3.5'

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: conchick
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: knowledge_base_for_artyom # Название бд
    volumes:
      - pg_data:/var/lib/postgresql/data # Том для хранения данных

volumes:
  pg_data:
